---
title: "cell_line_androgens"
author: "Taojun Wang"
date: "2024-01-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
```
## load required packages
```{r warning=FALSE}
library(ggplot2)
library(ape)
library(plyr)
library(RColorBrewer)
library(reshape2)
library(scales)
library(dplyr)
library(ggpubr) 
library(cowplot) 
library(readr)
library(stats)
library(readr)
```

# Load the data
```{r}
d1 <- read.csv("C:/UIUC documents/Androgen manuscript/Data and codes/AT metabolism_VPI 12708_LNCaP_dosage.csv") #read the d1
head(d1)
```
# define format
```{r}
format.A <-  theme_classic()+ theme(plot.title = element_text(size= 11, hjust=0.5, face="bold"))+ 
  theme(axis.text = element_text(size = 10)) + theme(axis.title = element_text(size = 10, face="bold")) + 
  theme(strip.text = element_text( size = 10, face= "bold")) + theme(legend.position = "none")

format.B <-  theme_classic()+ theme(plot.title = element_text(size= 11, hjust=0.5, face="bold"))+ 
  theme(axis.text = element_text(size = 10)) + theme(axis.title = element_text(size = 10, face="bold")) + 
  theme(strip.text = element_text( size = 10, face= "bold"))  
```
# color
```{r}
display.brewer.pal(n = 8, name = 'Dark2')
# Hexadecimal color specification 
brewer.pal(n = 8, name = "Dark2")
```

# Clarify the factors
```{r}
d1$Groups = factor(d1$Groups,order = TRUE, levels = c("CL", "AT", "epiAT"))
```
#Seperate the data
```{r}
d1.0.1nM <- subset(d1, Concentrations == "0.1nM")
d1.1nM <- subset(d1, Concentrations == "1nM")
d1.10nM <- subset(d1, Concentrations == "10nM")
```

# Summarize the d1
```{r}
d1.0.1nM_summary <- d1.0.1nM %>%
  group_by(Groups) %>%
  summarise(
    Mean = mean(Relative_cell_proliferation),
    SD = sd(Relative_cell_proliferation) # This avoids a grouped df warning in ggplot
  )

d1.0.1nM_summary$Relative_cell_proliferation <- d1.0.1nM_summary$Mean
head(d1.0.1nM)
head(d1.0.1nM_summary)

d1.1nM_summary <- d1.1nM %>%
  group_by(Groups) %>%
  summarise(
    Mean = mean(Relative_cell_proliferation),
    SD = sd(Relative_cell_proliferation) # This avoids a grouped df warning in ggplot
  )

d1.1nM_summary$Relative_cell_proliferation <- d1.1nM_summary$Mean
head(d1.1nM)
head(d1.1nM_summary)

d1.10nM_summary <- d1.10nM %>%
  group_by(Groups) %>%
  summarise(
    Mean = mean(Relative_cell_proliferation),
    SD = sd(Relative_cell_proliferation) # This avoids a grouped df warning in ggplot
  )

d1.10nM_summary$Relative_cell_proliferation <- d1.10nM_summary$Mean
head(d1.10nM)
head(d1.10nM_summary)

```

# Plot the p1
```{r}

p1 <- ggplot(d1.0.1nM, aes(x = Groups, y = Relative_cell_proliferation, fill = Groups)) +
  geom_bar(data = d1.0.1nM_summary, aes(y = Relative_cell_proliferation), stat = "identity", color="black") +
  geom_jitter(shape = 21, size = 3, stroke = 0.5, fill = "white", color = "black")+ ylim(0,2)+
  geom_errorbar(data = d1.0.1nM_summary, aes(ymin = Relative_cell_proliferation - SD, ymax = Relative_cell_proliferation + SD), 
                width = .2, position = position_dodge(0.9)) + scale_fill_manual(values = c( "#66A61E", "#E6AB02", "#A6761D", "#666666")) + scale_color_manual(values = c( "#66A61E", "#E6AB02", "#A6761D", "#666666")) + format.A +
  labs(x="Androgens (0.1 nM)", y="Relative cell proliferation")

print(p1)

p2 <- ggplot(d1.1nM, aes(x = Groups, y = Relative_cell_proliferation, fill = Groups)) +
  geom_bar(data = d1.1nM_summary, aes(y = Relative_cell_proliferation), stat = "identity", color="black") +
  geom_jitter(shape = 21, size = 3, stroke = 0.5, fill = "white", color = "black")+ ylim(0,2)+
  geom_errorbar(data = d1.1nM_summary, aes(ymin = Relative_cell_proliferation - SD, ymax = Relative_cell_proliferation + SD), 
                width = .2, position = position_dodge(0.9)) + scale_fill_manual(values = c( "#66A61E", "#E6AB02", "#A6761D", "#666666")) + scale_color_manual(values = c( "#66A61E", "#E6AB02", "#A6761D", "#666666")) + format.A +
  labs(x="Androgens (1 nM)", y="Relative cell proliferation")

print(p2)

p3 <- ggplot(d1.10nM, aes(x = Groups, y = Relative_cell_proliferation, fill = Groups)) +
  geom_bar(data = d1.10nM_summary, aes(y = Relative_cell_proliferation), stat = "identity", color="black") +
  geom_jitter(shape = 21, size = 3, stroke = 0.5, fill = "white", color = "black")+ ylim(0,2)+
  geom_errorbar(data = d1.10nM_summary, aes(ymin = Relative_cell_proliferation - SD, ymax = Relative_cell_proliferation + SD), 
                width = .2, position = position_dodge(0.9)) + scale_fill_manual(values = c( "#66A61E", "#E6AB02", "#A6761D", "#666666")) + scale_color_manual(values = c( "#66A61E", "#E6AB02", "#A6761D", "#666666")) + format.A +
  labs(x="Androgens (10 nM)", y="Relative cell proliferation")

print(p3)
# ggsave("C:/UIUC documents/Project of urinary microbes/Manuscript preparation/data analysis/enz_proliferation_androgens.pdf", height = 3.5, width = 5)

```

#statistics
```{r}
d1.0.1nM <- subset(d1, Concentrations == "0.1nM")
d1.1nM <- subset(d1, Concentrations == "1nM")
d1.10nM <- subset(d1, Concentrations == "10nM")

pairwise.t.test(d1.0.1nM$Relative_cell_proliferation, d1.0.1nM$Groups, p.adjust.method = "BH")
pairwise.t.test(d1.1nM$Relative_cell_proliferation, d1.1nM$Groups, p.adjust.method = "BH")
pairwise.t.test(d1.10nM$Relative_cell_proliferation, d1.10nM$Groups, p.adjust.method = "BH")

```

```{r}
AT_metabolism_VPI12708_LNCaP_dosage <- plot_grid(p1,p2,p3, labels=c("a", "b", "c"), ncol = 3, nrow = 1)

AT_metabolism_VPI12708_LNCaP_dosage

ggsave("C:/UIUC documents/Androgen manuscript/Data and codes/Figures/AT_metabolism_VPI12708_LNCaP_dosage.pdf", height = 3.5, width = 5, useDingbats = FALSE)

```

```{r}
sessionInfo()
```



















