---
title: "Bacterial_culture_steroids"
author: "Taojun Wang"
date: "02/15/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
```

## load required packages
```{r warning=FALSE}

library(ggplot2)
library(ape)
library(plyr)
library(RColorBrewer)
library(reshape2)
library(scales)
library(dplyr)
library(ggpubr) 
library(cowplot) 
library(readr)
library(stats)
library(readr)

```

# Load the data
```{r}
d1 <- read.csv("C:/UIUC documents/Androgen manuscript/Data and codes/AT metabolism_VPI 12708.csv") #read the data
head(d1)
```
# define format
```{r}
format.A <-  theme_classic()+ theme(plot.title = element_text(size= 11, hjust=0.5, face="bold"))+ 
  theme(axis.text = element_text(size = 10)) + theme(axis.title = element_text(size = 10, face="bold")) + 
  theme(strip.text = element_text( size = 10, face= "bold")) + theme(legend.position = "none")

format.B <-  theme_classic()+ theme(plot.title = element_text(size= 11, hjust=0.5, face="bold"))+ 
  theme(axis.text = element_text(size = 10)) + theme(axis.title = element_text(size = 10, face="bold")) + 
  theme(strip.text = element_text( size = 10, face= "bold"))  
```
# color
```{r}
display.brewer.pal(n = 8, name = 'Dark2')
# Hexadecimal color specification 
brewer.pal(n = 8, name = "Dark2")
```
# Clarify the factors
```{r}
d1$Time = factor(d1$Time,order = TRUE, levels = c("0h", "24h", "48h", "72h"))
```

# Summarize the Deoxycortisol
```{r}
d1_summary <- d1 %>%
  group_by(Time) %>%
  summarise(
    SD.AT = sd(AT, na.rm = TRUE),
    SD.epiAT = sd(epiAT, na.rm = TRUE),
   
    AT = mean(AT),
    epiAT = mean(epiAT)
  )
head(d1_summary)
#View(d1_summary)

```

# Plot VPI 12708 AT
```{r}
  
    p1 <- ggplot(d1, aes(x=Time, y=AT))+
      geom_bar(data = d1_summary, aes(x=Time, y= AT), stat = "identity", color="black") + 
      geom_errorbar(data = d1_summary,aes(x=Time, y= AT, ymin = AT-SD.AT, ymax = AT+SD.AT), width = 0.2)+ 
      scale_y_continuous( name = expression("Under curve area"), limits = c(0, 50000)) + 
     format.A + labs(title = "AT", x="Time (hours)")+
      scale_color_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D","#666666"))
     
    p1
   
```

# Plot VPI 12708 epiAT
```{r}

 p2 <- ggplot(d1, aes(x=Time, y=epiAT))+
      geom_bar(data = d1_summary, aes(x=Time, y= epiAT), stat = "identity", color="black") + 
      geom_errorbar(data = d1_summary,aes(x=Time, y= epiAT, ymin = epiAT-SD.epiAT, ymax = epiAT+SD.epiAT), width = 0.2)+ 
      scale_y_continuous( name = expression("Under curve area"), limits = c(0, 50000)) + 
     format.A + labs(title = "epiAT", x="Time (hours)")+
      scale_color_manual(values = c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D","#666666"))
     
 p2
 
```

# make one plot for the LC-MS analysis
```{r}

AT_metabolism_VPI12708<- plot_grid(p1,p2, labels=c("a", "b"), ncol = 2, nrow = 1)
print(AT_metabolism_VPI12708)
ggsave("C:/UIUC documents/Androgen manuscript/Data and codes/Figures/AT metabolism_VPI 12708.pdf", height = 3.5, width = 5, useDingbats = FALSE)

```

#statistics
```{r}

pairwise.t.test(d1$AT, d1$Time, p.adjust.method = "BH")
pairwise.t.test(d1$epiAT, d1$Time, p.adjust.method = "BH")

```

```{r}
sessionInfo()
```


